dist: xenial
language: java

env:
  global:
    - DEPLOY_OS=linux
    - DEPLOY_JDK=openjdk11
    - DEPLOY_REPO=nbbrd/picocsv

_java_windows_amd64: &_java_windows_amd64
  os: windows
  language: shell
  install:
    - choco install $TRAVIS_JDK_VERSION maven
    # fix: refresh $PATH, get $M2_HOME and append it to $PATH
    - eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
    - eval $(powershell -NonInteractive -Command 'write("export M2_HOME=`"" + ([Environment]::GetEnvironmentVariable("M2_HOME","Machine")).replace("\","/").replace("C:","/c").replace(";",":") + "`"")')
    - export PATH=${M2_HOME}/bin:${PATH}
  script:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn test -B

_java_linux_arm64: &_java_linux_arm64
  os: linux
  arch: arm64
  addons:
    apt:
      packages: maven

jobs:
  include:
    - name: "linux-amd64-openjdk8"
      jdk: openjdk8
      os: linux
      
    - name: "linux-amd64-openjdk11"
      jdk: openjdk11
      os: linux
      
    - name: "linux-amd64-openjdk-ea"
      jdk: openjdk-ea
      os: linux

    - name: "linux-arm64-openjdk11"
      jdk: openjdk11
      <<: *_java_linux_arm64
    
    - name: "macos-amd64-openjdk11"
      jdk: openjdk11
      os: osx
      
    - name: "windows-amd64-openjdk11"
      env: TRAVIS_JDK_VERSION=openjdk11
      <<: *_java_windows_amd64
      
  allow_failures:
    - jdk: openjdk-ea
    - os: windows
    - arch: arm64
    
deploy:
  # Maven snapshots from develop branch
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      tags: false
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Maven releases from tags
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    draft: true
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK && $TRAVIS_OS_NAME == $DEPLOY_OS

cache:
  directories:
    - $HOME/.m2
