name: Java8+ with Maven

on: [ push, pull_request ]

jobs:
  build-and-test-job:
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        experimental: [ false ]
        include:
          - java: '>11'
            os: ubuntu-latest
            experimental: true

    name: JDK${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and (headless) test with Maven
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B -ntp package

  snapshot-job:
    needs: build-and-test-job
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/heads/develop')
    strategy:
      matrix:
        java: [ 11 ]
        os: [ ubuntu-latest ]

    name: Snapshot on develop
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -ntp package -DskipTests=true

      - name: Deploy snapshot with Maven if settings defined
        run: test -f ci.settings.xml && mvn -B -ntp deploy -Dmaven.test.skip -s ci.settings.xml -P deploy-snapshots
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  release-job:
    needs: build-and-test-job
    if: startsWith(github.repository, 'nbbrd/') && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        java: [ 11 ]
        os: [ ubuntu-latest ]

    name: Release on tag
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -ntp package -DskipTests=true

      - name: Deploy with Maven if settings defined
        run: test -f ci.settings.xml && mvn -B -ntp deploy -Dmaven.test.skip -s ci.settings.xml -P deploy-releases
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Create dummy file if no assets
        run: test -d "binaries" || (mkdir binaries && echo "no assets" > binaries/no_assets.txt)

      - name: Create draft release and upload assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'binaries/*'
